### ISSUE TITLE
Multi point Bezier

### ISSUE THREAD

**Issue by davydov-vyacheslav** [NeuronRobotics/JCSG#11]
Hi,
I enjoy your fork! Thank you so much for it.

Unfortunately, I have one point what I can't get clear so far :(
I'd like to make bezier spline (of fixed thickness) which connects N points ....
I your code I see Extrude class, which has (I hope) appropriate method and I did see your example at http://commonwealthrobotics.com/JavaCAD/ExtrusionBezier/ , but unfortunately, still don't understand how to implement this :( 
Is there any other / additional documentation / examples about that?

Thanks in advance,
Slava

**Comment by madhephaestus** [comment]
So those examples are designed to work with the IDE for the cad, BowlerStudio http://commonwealthrobotics.com/ (it has installers Win/Mac/Ubuntu). You can run the examples, make your own copy, and run your changed copy to quickly understand the API and how to use it. 

A bezier curve is defined between the start point (always 0,0,0) and an end point. To concatenate a bunch of points, make a curve connecting each segment, then move it into place. If you find yourself doing this a lot, then it might be a good idea to make a function to make and place the segments.  In ASimpleBezier.groovy line 23-25 you move all of the segments in a given curve. Note that the Extrude produces a list of objects representing the slices that form the curve (this is a polygon only system, like the way 3d printing uses them). To make it one object, you union all the parts together. 

Best advice i can give is to fire up BowlerStudio and play with the tutorial steps.

**Comment by madhephaestus** [comment]
OK! i made a feature for this! 

See an example of its use here: https://github.com/madhephaestus/HonkyHorn/blob/main/HonkyHorn.groovy

**Comment by madhephaestus** [comment]
For others looking for this, the relevant code is:

```
import com.neuronrobotics.bowlerkernel.Bezier3d.*;
def URL="https://github.com/madhephaestus/HonkyHorn.git"
def numBezierPieces = 15
BezierEditor editor = new BezierEditor(ScriptingEngine.fileFromGit(URL, "bez.json"),numBezierPieces)
BezierEditor editor2 = new BezierEditor(ScriptingEngine.fileFromGit(URL, "bez2.json"),numBezierPieces)
BezierEditor editor3 = new BezierEditor(ScriptingEngine.fileFromGit(URL, "bez3.json"),numBezierPieces)

editor.addBezierToTheEnd(editor2)
editor.addBezierToTheEnd(editor3)
return [
	editor.get(),
	editor2.get(),
	editor3.get()
]
```
