### ISSUE TITLE
Synced properties 

### ISSUE THREAD

**Issue by jgandert** [NeuronRobotics/JCSG#20]
First of all, thanks for the fork! Working very well so far.

[OpenJSCAD](https://github.com/jscad/OpenJSCAD.org) has the concept of synced properties:

> The 'property' property of a solid can be used to store metadata for the object, for example the coordinate of a specific point of interest of the solid. Whenever the object is transformed (i.e. rotated, scaled or translated), the properties are transformed with it. So the property will keep pointing to the same point of interest even after several transformations have been applied to the solid.

I think that feature would be really useful to have in some form, since sometimes you want to connect two objects at certain points after they've been transformed multiple times. (I'm actually in that position.) 

AFAICS a simple way of implementing it would be adding a `Map<String, Vector3d>` field in the `CSG` whose values would be transformed as well, when `transformed` is called and copied to the new `CSG` in `historySync`.

That said, and I could be wrong, it might also be useful to allow this functionality for all `Transformable` objects (`CSG` included), so you could transform multiple related objects together without having to `union` them prematurely.

`Transformable` could be a marker interface or something like:

```java
public interface Transformable<T> {
    T transformed(Transform transform);
}
```

(I don't think it would be a good idea to use the existing properties field, since that would mean that every transform would have to iterate over each key-value and have to check each value for being transformable)

**Comment by madhephaestus** [comment]
I think maybe we want to do this with a design pattern of existing structures vs a new interface. 
I generally make Transforms 1st class citizens when i write code with this lib. like this:

https://commonwealthrobotics.com/JavaCAD/AdvancedTransforms/

conceptually, Transform objects are like sketch planes in traditional cad. You can cascade the transforms by applying a transform to a transform. In the end, i make a bunch of parts, put them in a list and apply the transform to all of them. 

If you are looking for "live motion" then this is a better method BECAUSE you would sunch the transform to the Affine of the JavaFX Mesh to move it without going through any JCSG code at all. This is how i get real time motions of JCSG objects in 3d space.

**Comment by jgandert** [comment]
> I think maybe we want to do this with a design pattern of existing structures vs a new interface.
I generally make Transforms 1st class citizens when i write code with this lib. like this:
> [...]
> conceptually, Transform objects are like sketch planes in traditional cad. You can cascade the transforms by applying a transform to a transform. In the end, i make a bunch of parts, put them in a list and apply the transform to all of them.

Makes sense. I think (it's been a while), in my use case I needed the intermediary position (as a result of a transform), to determine the next transform, so merging the transforms doesn't work there.

**Comment by madhephaestus** [comment]
Intermediate transforms are always accessible, just stor what you need to a variable. The transform library has 2 forms of oppeations, apply to the self object, or apply to a new object and return the moved transform. All intermediate transforms you want are accessible.

**Comment by jgandert** [comment]
@madhephaestus Hmm, you're right. 

But does this really disqualify this idea (synced properties)? You could after all, merge transforms and then apply them to the object (or do it directly on the mesh as you said), thus avoiding applying every single transform to every single subtransformable.

It's possible I'm missing something, as I haven't worked that much with 3D.

**Comment by madhephaestus** [comment]
tell you what, can you sketch a little example on paper and ill show you some psudo-code of how to do it?

**Comment by jgandert** [comment]
Basically I want to be able to provide a UI where users can apply transforms and then based on those transforms, certain points are also transformed. Users could then say, I want this other object to be at the same height as this transformed corner point but 3 apart (on the x axis). 

Or the object changes somehow as in the following:

> can you sketch a little example

Happy to do that! Here's an example (d is an arbitrary number):

![cube rotation subtransformable](https://user-images.githubusercontent.com/3063858/113705367-a4196a80-96dd-11eb-9a61-948d0679b84a.png)

To be clear, I'm not saying this can't be done any other way. (I'm pretty sure it can.) I'm just saying that subtransformable seem like a useful, flexible and easy to understand way to do this.

**Comment by madhephaestus** [comment]
Ok i created a quick sample that does what you sketched out

https://github.com/madhephaestus/subtransformableexample/blob/master/subtrans.groovy

```
double d=15
double rot =80
//First create a point and a cube, the point representing a corner of the cube
Vector3d point = Vector3d.xyz(20,20, 0);
CSG cube  = new Cube(	point.x*2,// X dimention
			point.y*2,// Y dimention
			5//  Z dimention
			).toCSG()
println "Point starts at: "+point
// Make the transfomr of the first 2 moves
Transform frame2 = new Transform().rotz(-rot).movey(d)
//Apply the first motion to both the point and the cube
CSG cube2=cube.transformed(frame2)
Vector3d point2 = point.transformed(frame2)
println "Point2 starts at: "+point2+" from "+point
// Calculate the offset based on where the point ended up
double offseCalculated = -0.75*point2.getY()
println "Offset calculated "+offseCalculated
//Create the final frame by moveing by the calculated value
Transform frame3 = frame2.movey(offseCalculated)
// apply that final transform to the cube and return it, also apply the final frame to the 
// original point to get the final location
CSG cube3=cube.transformed(frame3)
Vector3d point3 = point.transformed(frame3)
println "Final location of the point "+point3
return cube3
```

**Comment by jgandert** [comment]
@madhephaestus Thank you! I guess what I like about subtransformable is that it's just one transform call, and it takes care of all of the points that relate to this object.

That said, I have currently implemented this using a CSG wrapper class, so I guess we can close this now.
