### ISSUE TITLE
Union is resulting in parts of the object being cut off

### ISSUE THREAD

**Issue by jgandert** [NeuronRobotics/JCSG#34]
In a project I'm working on, there are several small objects, which have already been unionized:

![Screenshot_20230402_132814](https://user-images.githubusercontent.com/3063858/229350027-36010659-b68f-457f-8dc1-c0ed2e7830e2.png)

Additionally, there is also a part that is connecting two of those objects:

![Screenshot_20230402_132954](https://user-images.githubusercontent.com/3063858/229350032-3f2ded18-7678-4e3a-b4dc-9324e2868d77.png)

When creating a union of these CSGs, the result is severally cut off.

![Screenshot_20230402_133003](https://user-images.githubusercontent.com/3063858/229350036-b12949f1-782f-43af-824e-724388f561ac.png)

I've created a gist that can reproduce this issue (maybe a simpler example might be possible):

https://gist.github.com/CreamyCookie/7e5948c4460ad65fa133920da9f418d9

**Comment by madhephaestus** [comment]
this looks to be what happens when a polygon is created with holes in it or has a face defined inside out. To create the intermediate shape, i would recommend using the extrude slice feature: https://commonwealthrobotics.com/JavaCAD/ExtrudePolygon/ instead of instantiating the list of polygons by hand. I suspect one of your polygons is being defined with its normal pointing the wrong way. Generally i use the primitives and CSG operations to make complex shapes. 

In fact there are quite a few CSG operations that would make these shapes easier to construct: https://commonwealthrobotics.com/JavaCAD/Overview/

**Comment by madhephaestus** [comment]
Also, in case you were not aware, there is an IDE for JCSG called BowlerStudio: https://commonwealthrobotics.com/ You can use the IDE to get your CSG operations all worked out, and send them directly to print, or then embed that code in a larger application.

**Comment by jgandert** [comment]
> this looks to be what happens when a polygon is created with holes in it or has a face defined inside out. To create the intermediate shape, i would recommend using the extrude slice feature: https://commonwealthrobotics.com/JavaCAD/ExtrudePolygon/ instead of instantiating the list of polygons by hand. I suspect one of your polygons is being defined with its normal pointing the wrong way. Generally i use the primitives and CSG operations to make complex shapes.
> 
> In fact there are quite a few CSG operations that would make these shapes easier to construct: https://commonwealthrobotics.com/JavaCAD/Overview/

Thank you so much! That must have been the reason. I've now switched to using QuickHull and it works. I guess that's not very performant, but I think extrudes don't work for my case, or at least I don't really understand them yet. 

Is there an example of connecting two squares (one of which is rotated in both x, y and z) using extrudes? 

I guess an alternative would be finding out how to ensure the normal is pointing the right direction.

**Comment by madhephaestus** [comment]
since the connection shape is convex, QuickHull will also work for you to make the connecting shape given you already have the corners defined.
